CREATE TABLE "USERS_TBL" (
  "USER_ID" varchar(10) PRIMARY KEY,
  "USERNAME" varchar(50) UNIQUE,
  "PASSWORD" varchar(255),
  "WAREHOUSE_ID" varchar(25)
);

CREATE TABLE "ORDERS_TBL" (
  "ORDER_ID" varchar(20) PRIMARY KEY,
  "SUPPLIER_ID" varchar(10),
  "RECEIVER_ID" varchar(10),
  "CREATED_BY" varchar(20),
  "CREATED_AT" timestamp,
  "UPDATE_AT" timestamp,
  "STATUS" int,
  "STORED_AT" timestamp,
  "WAREHOUSE_ID" varchar(25),
  "DELIVERED_AT" timestamp,
  "FAILED_DELIVERIES" int DEFAULT 0,
  "RETURN_AT" timestamp
);

CREATE TABLE "SUPPLIERS_TBL" (
  "SUPPLIER_ID" varchar(10) PRIMARY KEY,
  "NAME" varchar(50),
  "ADDRESS" varchar(200),
  "PHONE" varchar(15),
  "LATITUDE" decimal(9,6),
  "LONGITUDE" decimal(9,6),
  "EMAIL" varchar(255)
);

CREATE TABLE "RECEIVERS_TBL" (
  "RECEIVER_ID" varchar(10) PRIMARY KEY,
  "NAME" varchar(50),
  "PHONE" varchar(15),
  "ADDRESS" varchar(200),
  "LATITUDE" decimal(9,6),
  "LONGITUDE" decimal(9,6),
  "EMAIL" varchar(255)
);

CREATE TABLE "WAREHOUSE_TBL" (
  "WAREHOUSE_ID" varchar(25) PRIMARY KEY,
  "NAME" varchar(50),
  "ADDRESS" varchar(200),
  "LATITUDE" decimal(9,6),
  "LONGITUDE" decimal(9,6),
  "CAPACITY" int
);

CREATE TABLE "ORDER_HISTORY_TBL" (
  "HISTORY_ID" varchar(10) PRIMARY KEY,
  "PERFORMED_BY" varchar(50),
  "PERFORMED_AT" timestamp,
  "ORDER_ID" varchar(20),
  "WAREHOUSE_ID" varchar(25),
  "STATUS" int,
  "FAILURE_REASON" varchar(200)
);

ALTER TABLE "USERS_TBL" ADD FOREIGN KEY ("WAREHOUSE_ID") REFERENCES "WAREHOUSE_TBL" ("WAREHOUSE_ID");

ALTER TABLE "ORDERS_TBL" ADD FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIERS_TBL" ("SUPPLIER_ID");

ALTER TABLE "ORDERS_TBL" ADD FOREIGN KEY ("RECEIVER_ID") REFERENCES "RECEIVERS_TBL" ("RECEIVER_ID");

ALTER TABLE "ORDERS_TBL" ADD FOREIGN KEY ("WAREHOUSE_ID") REFERENCES "WAREHOUSE_TBL" ("WAREHOUSE_ID");

ALTER TABLE "ORDER_HISTORY_TBL" ADD FOREIGN KEY ("PERFORMED_BY") REFERENCES "USERS_TBL" ("USER_ID");

ALTER TABLE "ORDER_HISTORY_TBL" ADD FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS_TBL" ("ORDER_ID");

ALTER TABLE "ORDER_HISTORY_TBL" ADD FOREIGN KEY ("WAREHOUSE_ID") REFERENCES "WAREHOUSE_TBL" ("WAREHOUSE_ID");
